name: ss
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  change_app_package_name: ^1.4.0
  flutter:
    sdk: flutter
  flutter_intro: ^3.4.0
  flutter_launcher_icons: "^0.14.3"
  in_app_update: ^4.2.3
  package_info_plus: ^8.2.0
  shared_preferences: ^2.5.1
  url_launcher: ^6.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/launch_logo.png
  fonts:
    - family: H1
      fonts:
        - asset: assets/fonts/Oswald.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launch_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/launch_logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/images/launch_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/launch_logo.png"